name: Pinspaces-CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1

    - name: Installer
      run: iscc .\build\PinspacesSetup.iss

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: PinspacesBinaries
        path: Pinspaces\bin\Release\net5.0-windows\publish\

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: Pinspaces
        files: |
          bin/PinspacesSetup.exe