name: Pinspaces-CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      VERSION: 0.0.0.${GITHUB_RUN_NUMBER}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Pinspaces
      run: dotnet publish Pinspaces /p:Version=${{ env.VERSION }} --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1

    - name: Publish Pinspaces.Core.Controls
      run: dotnet publish Pinspaces.Core.Controls /p:Version=${{ env.VERSION }} --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1 --output Pinspaces\bin\Release\publish\plugins\Pinspaces.Core.Controls\

    - name: Publish Pinspaces.Shell
      run: dotnet publish Pinspaces.Shell /p:Version=${{ env.VERSION }} --no-restore --framework net5.0-windows --configuration Release -maxcpucount:1 --output Pinspaces\bin\Release\publish\plugins\Pinspaces.Shell\

    - name: Installer
      run: iscc .\build\PinspacesSetup.iss

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: PinspacesBinaries
        path: Pinspaces\bin\Release\publish\

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: Pinspaces
        path: bin/PinspacesSetup.exe